# create docker file for archlinux
FROM archlinux:latest as builder
RUN pacman --noconfirm -Syyu base-devel git rustup  \
               core/openssl-1.1 binutils fakeroot gcc \
               sudo go core/libnsl core/python
RUN useradd -m build  && echo 'build ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/build 
USER build
RUN rustup default stable
RUN git clone https://github.com/Morganamilo/paru.git /tmp/paru && cd /tmp/paru && cargo build --release && \
    sudo cp /tmp/paru/target/release/paru /usr/bin/paru
RUN paru -S fnm
FROM archlinux:latest as Main
COPY --from=builder  /usr/bin/fnm /usr/bin/
RUN pacman -Syyu --noconfirm stow starship neovim fzf bat exa git-delta mcfly lazygit git fd ripgrep direnv thefuck zoxide tmux zsh sudo gcc go unzip shellcheck flake8 cmake make && rm -rf /var/cache/pacman/pkg/*
WORKDIR /root/
RUN git clone https://github.com/elmomk/dotfiles
RUN cd dotfiles && stow -t ~ zsh-personal tmux mo-vim starship
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    echo "[[ -f ~/.zshrc-personal ]] && . ~/.zshrc-personal" >> ~/.zshrc
RUN fnm install --latest
RUN nvim --headless +PlugInstall +qall +Mason
